{
 "title": "Dashboard transcendence",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=~\"redis.*|backend.*|postgre.*|nginx.*|prometheus.*|cadvisor.*|grafana.*\", job=\"cadvisor\"} / (1024 * 1024)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network Traffic Overview (receive data / 15s)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=~\"redis.*|backend.*|postgre.*|nginx.*|prometheus.*|cadvisor.*|grafana.*\", job=\"cadvisor\"}[15s]) / 1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=~\"redis.*|backend.*|postgre.*|nginx.*|prometheus.*|cadvisor.*|grafana.*\", job=\"cadvisor\"}[10s]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Docker last seen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "container_last_seen{container_label_com_docker_compose_service=~\"redis.*|backend.*|postgre.*|nginx.*|prometheus.*|cadvisor.*|grafana.*\", job=\"cadvisor\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}